name : Tests
on : push
jobs:
  test:
    runs-on: ${{matrix.os}}
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    strategy : 
      matrix :
        os: [macos-latest, ubuntu-latest]
    steps : 
      - name : Checkout
        uses: actions/checkout@v3

      - uses : pnpm/action-setup@v2
        with : 
          version : 7.23.0

      - name : Install dependencies
        run: pnpm install --no-frozen-lockfile


